### ISSUE TITLE
Permutation error with latest version

### ISSUE THREAD

**Issue by nmoran** [under-Peter/OMEinsum.jl#136] opened 2022-01-09 22:48 UTC
Following contraction

```
EinCode(((1,2,3),(2,)),(1,3))(ones(2,2,1), ones(2))
```

works with 0.6.7 but with 0.6.8 results in following

```
ERROR: ArgumentError: no valid permutation of dimensions
Stacktrace:
 [1] permutedims(B::Matrix{Float64}, perm::Vector{Int64})
   @ Base ./multidimensional.jl:1491
 [2] tensorpermute(A::Array{Float64, 3}, perm::Tuple{Int64, Int64, Int64})
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/utils.jl:113
 [3] einsum(#unused#::OMEinsum.Permutedims, ixs::Tuple{Vector{Int64}}, iy::Vector{Int64}, xs::Tuple{Array{Float64, 3}}, size_dict::Dict{Int64, Int64})
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/unaryrules.jl:175
 [4] simplify_unary(ix::Vector{Int64}, iy::Vector{Int64}, x::Array{Float64, 3}, size_dict::Dict{Int64, Int64})
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/binaryrules.jl:238
 [5] einsum(#unused#::OMEinsum.DefaultRule, ixs::Vector{Vector{Int64}}, iy::Vector{Int64}, xs::Tuple{Any, Any}, size_dict::Dict{Int64, Int64})
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/binaryrules.jl:225
 [6] einsum(code::DynamicEinCode{Int64}, xs::Tuple, size_dict::Dict{Int64, Int64})
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/interfaces.jl:200
 [7] (::DynamicEinCode{Int64})(::Any, ::Vararg{Any, N} where N; size_info::Nothing)
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/interfaces.jl:42
 [8] (::DynamicEinCode{Int64})(::Any, ::Vararg{Any, N} where N)
   @ OMEinsum ~/.julia/packages/OMEinsum/8NhV1/src/interfaces.jl:41
 [9] top-level scope
   @ REPL[11]:1
```

**Comment by GiggleLiu** [comment] 2022-01-10 00:26
Thanks for the bug report, just confirmed it is a bug introduced by #135 . Will fix it ASAP.

**Comment by GiggleLiu** [comment] 2022-01-10 00:44
After merge and tag #137 , this bug will be fixed. It turns out to be a very dangerous bug that will raise an error whenever there is a tensor dimension being 1. Thanks for finding this bug!

**Closed** 2022-01-10 00:56 UTC
Labels: bug

**Comment by nmoran** [comment] 2022-01-11 22:29
Great, thanks for very speedy resolution!
